name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root
          poetry run pip install python-multipart

      - name: Run Tests
        run: poetry run python -m pytest tests/
        env:
          PYTHONPATH: .
          DATABASE_URL: sqlite:///./test.db
          SECRET_KEY: test_secret_key_for_ci
